server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: accountService
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: transactionService
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**