spring:
  application:
    name: eureka-discovery-service
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8083
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka